CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY, 
  name VARCHAR(255),
  email VARCHAR(255),
  password VARCHAR(255)
  );

CREATE TABLE IF NOT EXISTS rooms (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255),
  password VARCHAR(255)
);

-- CREATE TABLE IF NOT EXISTS userRoom (
--   userId INT NOT NULL,
--   roomId INT NOT NULL, 
--   PRIMARY KEY (userId, roomId),
--   FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
--   FOREIGN KEY (roomId) REFERENCES rooms(id) ON DELETE CASCADE ON UPDATE CASCADE
-- );